import { Inter } from "next/font/google";
import "./globals.css";
import Nav from '../components/Nav'
import SliderComponent from "../components/SliderComponent";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <Nav />
      <main id="home" className="mt-24">
          <SliderComponent />
          {children}
        </main>
      </body>
    </html>
  );
}
